/**
 * Constantes pour les APIs et données astrologiques/bien-être
 */

import { ZodiacSignInfo, ZodiacSignKey, MoonPhaseName, MoonPhase, NumerologyProfile } from './types';

// ============================================
// Informations complètes des signes du zodiaque
// ============================================

export const ZODIAC_SIGNS: Record<ZodiacSignKey, ZodiacSignInfo> = {
  aries: {
    key: 'aries',
    name: 'Aries',
    nameFr: 'Bélier',
    symbol: '♈',
    emoji: '♈',
    element: 'fire',
    elementFr: 'Feu',
    modality: 'cardinal',
    modalityFr: 'Cardinal',
    ruler: 'Mars',
    rulerFr: 'Mars',
    dateRange: 'March 21 - April 19',
    dateRangeFr: '21 mars - 19 avril',
    traits: ['Courageous', 'Energetic', 'Optimistic', 'Honest', 'Passionate'],
    traitsFr: ['Courageux', 'Énergique', 'Optimiste', 'Honnête', 'Passionné'],
    description: 'The first sign of the zodiac, Aries is known for its pioneering spirit and boundless energy.',
    descriptionFr: 'Premier signe du zodiaque, le Bélier est connu pour son esprit pionnier et son énergie débordante. Audacieux et déterminé, il n\'hésite pas à prendre des initiatives.',
    color: '#E53E3E',
    colorFr: 'Rouge',
  },
  taurus: {
    key: 'taurus',
    name: 'Taurus',
    nameFr: 'Taureau',
    symbol: '♉',
    emoji: '♉',
    element: 'earth',
    elementFr: 'Terre',
    modality: 'fixed',
    modalityFr: 'Fixe',
    ruler: 'Venus',
    rulerFr: 'Vénus',
    dateRange: 'April 20 - May 20',
    dateRangeFr: '20 avril - 20 mai',
    traits: ['Reliable', 'Patient', 'Practical', 'Devoted', 'Responsible'],
    traitsFr: ['Fiable', 'Patient', 'Pratique', 'Dévoué', 'Responsable'],
    description: 'Taurus is known for its stability, practicality, and love for the finer things in life.',
    descriptionFr: 'Le Taureau est reconnu pour sa stabilité, son côté pratique et son amour des bonnes choses de la vie. Sensuel et déterminé, il construit avec patience.',
    color: '#38A169',
    colorFr: 'Vert',
  },
  gemini: {
    key: 'gemini',
    name: 'Gemini',
    nameFr: 'Gémeaux',
    symbol: '♊',
    emoji: '♊',
    element: 'air',
    elementFr: 'Air',
    modality: 'mutable',
    modalityFr: 'Mutable',
    ruler: 'Mercury',
    rulerFr: 'Mercure',
    dateRange: 'May 21 - June 20',
    dateRangeFr: '21 mai - 20 juin',
    traits: ['Adaptable', 'Outgoing', 'Intelligent', 'Curious', 'Witty'],
    traitsFr: ['Adaptable', 'Sociable', 'Intelligent', 'Curieux', 'Spirituel'],
    description: 'Gemini is known for its versatility, communication skills, and intellectual curiosity.',
    descriptionFr: 'Les Gémeaux sont connus pour leur polyvalence, leurs talents de communication et leur curiosité intellectuelle. Vifs et adaptables, ils adorent apprendre.',
    color: '#ECC94B',
    colorFr: 'Jaune',
  },
  cancer: {
    key: 'cancer',
    name: 'Cancer',
    nameFr: 'Cancer',
    symbol: '♋',
    emoji: '♋',
    element: 'water',
    elementFr: 'Eau',
    modality: 'cardinal',
    modalityFr: 'Cardinal',
    ruler: 'Moon',
    rulerFr: 'Lune',
    dateRange: 'June 21 - July 22',
    dateRangeFr: '21 juin - 22 juillet',
    traits: ['Intuitive', 'Sentimental', 'Compassionate', 'Protective', 'Loyal'],
    traitsFr: ['Intuitif', 'Sentimental', 'Compatissant', 'Protecteur', 'Loyal'],
    description: 'Cancer is known for its emotional depth, nurturing nature, and strong family bonds.',
    descriptionFr: 'Le Cancer est connu pour sa profondeur émotionnelle, sa nature protectrice et ses liens familiaux forts. Sensible et intuitif, il crée un foyer chaleureux.',
    color: '#B7B7B7',
    colorFr: 'Argent',
  },
  leo: {
    key: 'leo',
    name: 'Leo',
    nameFr: 'Lion',
    symbol: '♌',
    emoji: '♌',
    element: 'fire',
    elementFr: 'Feu',
    modality: 'fixed',
    modalityFr: 'Fixe',
    ruler: 'Sun',
    rulerFr: 'Soleil',
    dateRange: 'July 23 - August 22',
    dateRangeFr: '23 juillet - 22 août',
    traits: ['Creative', 'Passionate', 'Generous', 'Warm-hearted', 'Cheerful'],
    traitsFr: ['Créatif', 'Passionné', 'Généreux', 'Chaleureux', 'Joyeux'],
    description: 'Leo is known for its dramatic flair, creativity, and natural leadership abilities.',
    descriptionFr: 'Le Lion est connu pour son charisme, sa créativité et son leadership naturel. Généreux et rayonnant, il aime briller et inspirer les autres.',
    color: '#D69E2E',
    colorFr: 'Or',
  },
  virgo: {
    key: 'virgo',
    name: 'Virgo',
    nameFr: 'Vierge',
    symbol: '♍',
    emoji: '♍',
    element: 'earth',
    elementFr: 'Terre',
    modality: 'mutable',
    modalityFr: 'Mutable',
    ruler: 'Mercury',
    rulerFr: 'Mercure',
    dateRange: 'August 23 - September 22',
    dateRangeFr: '23 août - 22 septembre',
    traits: ['Analytical', 'Kind', 'Hardworking', 'Practical', 'Loyal'],
    traitsFr: ['Analytique', 'Bienveillant', 'Travailleur', 'Pratique', 'Loyal'],
    description: 'Virgo is known for its attention to detail, analytical mind, and desire to help others.',
    descriptionFr: 'La Vierge est connue pour son attention aux détails, son esprit analytique et son désir d\'aider les autres. Perfectionniste et dévouée, elle excelle dans le service.',
    color: '#48BB78',
    colorFr: 'Vert forêt',
  },
  libra: {
    key: 'libra',
    name: 'Libra',
    nameFr: 'Balance',
    symbol: '♎',
    emoji: '♎',
    element: 'air',
    elementFr: 'Air',
    modality: 'cardinal',
    modalityFr: 'Cardinal',
    ruler: 'Venus',
    rulerFr: 'Vénus',
    dateRange: 'September 23 - October 22',
    dateRangeFr: '23 septembre - 22 octobre',
    traits: ['Diplomatic', 'Fair-minded', 'Social', 'Gracious', 'Peaceful'],
    traitsFr: ['Diplomate', 'Équitable', 'Social', 'Gracieux', 'Pacifique'],
    description: 'Libra is known for its love of harmony, beauty, and balanced relationships.',
    descriptionFr: 'La Balance est connue pour son amour de l\'harmonie, de la beauté et des relations équilibrées. Élégante et diplomate, elle recherche la justice.',
    color: '#ED8936',
    colorFr: 'Rose',
  },
  scorpio: {
    key: 'scorpio',
    name: 'Scorpio',
    nameFr: 'Scorpion',
    symbol: '♏',
    emoji: '♏',
    element: 'water',
    elementFr: 'Eau',
    modality: 'fixed',
    modalityFr: 'Fixe',
    ruler: 'Pluto',
    rulerFr: 'Pluton',
    dateRange: 'October 23 - November 21',
    dateRangeFr: '23 octobre - 21 novembre',
    traits: ['Resourceful', 'Brave', 'Passionate', 'Stubborn', 'Loyal'],
    traitsFr: ['Ingénieux', 'Courageux', 'Passionné', 'Déterminé', 'Loyal'],
    description: 'Scorpio is known for its intensity, depth, and transformative power.',
    descriptionFr: 'Le Scorpion est connu pour son intensité, sa profondeur et sa capacité de transformation. Mystérieux et magnétique, il va au fond des choses.',
    color: '#9B2C2C',
    colorFr: 'Bordeaux',
  },
  sagittarius: {
    key: 'sagittarius',
    name: 'Sagittarius',
    nameFr: 'Sagittaire',
    symbol: '♐',
    emoji: '♐',
    element: 'fire',
    elementFr: 'Feu',
    modality: 'mutable',
    modalityFr: 'Mutable',
    ruler: 'Jupiter',
    rulerFr: 'Jupiter',
    dateRange: 'November 22 - December 21',
    dateRangeFr: '22 novembre - 21 décembre',
    traits: ['Generous', 'Idealistic', 'Adventurous', 'Honest', 'Optimistic'],
    traitsFr: ['Généreux', 'Idéaliste', 'Aventurier', 'Honnête', 'Optimiste'],
    description: 'Sagittarius is known for its love of freedom, adventure, and philosophical thinking.',
    descriptionFr: 'Le Sagittaire est connu pour son amour de la liberté, de l\'aventure et de la philosophie. Optimiste et explorateur, il cherche toujours à élargir ses horizons.',
    color: '#805AD5',
    colorFr: 'Violet',
  },
  capricorn: {
    key: 'capricorn',
    name: 'Capricorn',
    nameFr: 'Capricorne',
    symbol: '♑',
    emoji: '♑',
    element: 'earth',
    elementFr: 'Terre',
    modality: 'cardinal',
    modalityFr: 'Cardinal',
    ruler: 'Saturn',
    rulerFr: 'Saturne',
    dateRange: 'December 22 - January 19',
    dateRangeFr: '22 décembre - 19 janvier',
    traits: ['Responsible', 'Disciplined', 'Self-control', 'Ambitious', 'Patient'],
    traitsFr: ['Responsable', 'Discipliné', 'Maître de soi', 'Ambitieux', 'Patient'],
    description: 'Capricorn is known for its ambition, discipline, and practical approach to life.',
    descriptionFr: 'Le Capricorne est connu pour son ambition, sa discipline et son approche pratique de la vie. Persévérant et responsable, il gravit les sommets.',
    color: '#4A5568',
    colorFr: 'Gris foncé',
  },
  aquarius: {
    key: 'aquarius',
    name: 'Aquarius',
    nameFr: 'Verseau',
    symbol: '♒',
    emoji: '♒',
    element: 'air',
    elementFr: 'Air',
    modality: 'fixed',
    modalityFr: 'Fixe',
    ruler: 'Uranus',
    rulerFr: 'Uranus',
    dateRange: 'January 20 - February 18',
    dateRangeFr: '20 janvier - 18 février',
    traits: ['Progressive', 'Original', 'Independent', 'Humanitarian', 'Intellectual'],
    traitsFr: ['Progressiste', 'Original', 'Indépendant', 'Humanitaire', 'Intellectuel'],
    description: 'Aquarius is known for its originality, independence, and humanitarian vision.',
    descriptionFr: 'Le Verseau est connu pour son originalité, son indépendance et sa vision humanitaire. Innovateur et avant-gardiste, il pense à l\'avenir de l\'humanité.',
    color: '#4299E1',
    colorFr: 'Bleu électrique',
  },
  pisces: {
    key: 'pisces',
    name: 'Pisces',
    nameFr: 'Poissons',
    symbol: '♓',
    emoji: '♓',
    element: 'water',
    elementFr: 'Eau',
    modality: 'mutable',
    modalityFr: 'Mutable',
    ruler: 'Neptune',
    rulerFr: 'Neptune',
    dateRange: 'February 19 - March 20',
    dateRangeFr: '19 février - 20 mars',
    traits: ['Compassionate', 'Artistic', 'Intuitive', 'Gentle', 'Wise'],
    traitsFr: ['Compatissant', 'Artistique', 'Intuitif', 'Doux', 'Sage'],
    description: 'Pisces is known for its empathy, creativity, and spiritual depth.',
    descriptionFr: 'Les Poissons sont connus pour leur empathie, leur créativité et leur profondeur spirituelle. Rêveurs et intuitifs, ils sont connectés à l\'invisible.',
    color: '#9F7AEA',
    colorFr: 'Lavande',
  },
};

export const ZODIAC_SIGNS_ARRAY: ZodiacSignKey[] = [
  'aries', 'taurus', 'gemini', 'cancer', 'leo', 'virgo',
  'libra', 'scorpio', 'sagittarius', 'capricorn', 'aquarius', 'pisces'
];

// ============================================
// Phases lunaires
// ============================================

export const MOON_PHASES: Record<MoonPhaseName, Omit<MoonPhase, 'illumination' | 'age'>> = {
  'New Moon': {
    phase: 'New Moon',
    phaseFr: 'Nouvelle Lune',
    emoji: '🌑',
    description: 'Time for new beginnings and setting intentions.',
    descriptionFr: 'Temps pour les nouveaux départs et poser ses intentions. Moment idéal pour la méditation et l\'introspection.',
    rituals: ['Set intentions', 'Start new projects', 'Plant seeds'],
    ritualsFr: ['Poser ses intentions', 'Commencer de nouveaux projets', 'Planter des graines'],
  },
  'Waxing Crescent': {
    phase: 'Waxing Crescent',
    phaseFr: 'Premier Croissant',
    emoji: '🌒',
    description: 'Time to take action on your intentions.',
    descriptionFr: 'Moment de passer à l\'action sur vos intentions. L\'énergie croît, c\'est le temps d\'agir.',
    rituals: ['Take action', 'Build momentum', 'Stay focused'],
    ritualsFr: ['Passer à l\'action', 'Construire l\'élan', 'Rester concentré'],
  },
  'First Quarter': {
    phase: 'First Quarter',
    phaseFr: 'Premier Quartier',
    emoji: '🌓',
    description: 'Time to overcome challenges and make decisions.',
    descriptionFr: 'Temps de surmonter les défis et prendre des décisions. Les obstacles peuvent apparaître.',
    rituals: ['Face challenges', 'Make decisions', 'Stay committed'],
    ritualsFr: ['Affronter les défis', 'Prendre des décisions', 'Rester engagé'],
  },
  'Waxing Gibbous': {
    phase: 'Waxing Gibbous',
    phaseFr: 'Lune Gibbeuse Croissante',
    emoji: '🌔',
    description: 'Time to refine and perfect your work.',
    descriptionFr: 'Moment d\'affiner et perfectionner votre travail. Ajustez vos efforts avant la pleine lune.',
    rituals: ['Refine plans', 'Perfect details', 'Prepare for completion'],
    ritualsFr: ['Affiner les plans', 'Perfectionner les détails', 'Préparer l\'achèvement'],
  },
  'Full Moon': {
    phase: 'Full Moon',
    phaseFr: 'Pleine Lune',
    emoji: '🌕',
    description: 'Time for completion, celebration, and release.',
    descriptionFr: 'Temps d\'accomplissement, de célébration et de libération. Énergie à son maximum.',
    rituals: ['Celebrate achievements', 'Release what no longer serves', 'Charge crystals'],
    ritualsFr: ['Célébrer les accomplissements', 'Libérer ce qui ne sert plus', 'Charger les cristaux'],
  },
  'Waning Gibbous': {
    phase: 'Waning Gibbous',
    phaseFr: 'Lune Gibbeuse Décroissante',
    emoji: '🌖',
    description: 'Time for gratitude and sharing wisdom.',
    descriptionFr: 'Moment de gratitude et de partage de sagesse. Transmettez ce que vous avez appris.',
    rituals: ['Express gratitude', 'Share knowledge', 'Give back'],
    ritualsFr: ['Exprimer la gratitude', 'Partager la connaissance', 'Donner en retour'],
  },
  'Last Quarter': {
    phase: 'Last Quarter',
    phaseFr: 'Dernier Quartier',
    emoji: '🌗',
    description: 'Time for letting go and forgiveness.',
    descriptionFr: 'Temps de lâcher-prise et de pardon. Libérez-vous des fardeaux émotionnels.',
    rituals: ['Let go of the past', 'Forgive', 'Release attachments'],
    ritualsFr: ['Lâcher le passé', 'Pardonner', 'Libérer les attachements'],
  },
  'Waning Crescent': {
    phase: 'Waning Crescent',
    phaseFr: 'Dernier Croissant',
    emoji: '🌘',
    description: 'Time for rest, reflection, and preparation.',
    descriptionFr: 'Temps de repos, réflexion et préparation. Rechargez vos énergies avant le nouveau cycle.',
    rituals: ['Rest and restore', 'Meditate', 'Prepare for new cycle'],
    ritualsFr: ['Se reposer', 'Méditer', 'Préparer le nouveau cycle'],
  },
};

// ============================================
// Numérologie - Chemins de vie
// ============================================

export const LIFE_PATH_NUMBERS: Record<number, Omit<NumerologyProfile, 'lifePathNumber'>> = {
  1: {
    lifePathName: 'The Leader',
    lifePathNameFr: 'Le Leader',
    description: 'Independent, ambitious, and pioneering.',
    descriptionFr: 'Vous êtes né pour diriger et innover. Indépendant et ambitieux, vous tracez votre propre chemin avec détermination.',
    strengths: ['Leadership', 'Independence', 'Creativity', 'Courage'],
    strengthsFr: ['Leadership', 'Indépendance', 'Créativité', 'Courage'],
    challenges: ['Impatience', 'Stubbornness', 'Self-doubt'],
    challengesFr: ['Impatience', 'Entêtement', 'Doute de soi'],
    compatibleNumbers: [1, 5, 7],
  },
  2: {
    lifePathName: 'The Diplomat',
    lifePathNameFr: 'Le Diplomate',
    description: 'Cooperative, sensitive, and peacemaking.',
    descriptionFr: 'Vous êtes né pour créer l\'harmonie et la paix. Sensible et coopératif, vous excellez dans les relations.',
    strengths: ['Diplomacy', 'Cooperation', 'Intuition', 'Patience'],
    strengthsFr: ['Diplomatie', 'Coopération', 'Intuition', 'Patience'],
    challenges: ['Over-sensitivity', 'Indecision', 'Fear of conflict'],
    challengesFr: ['Hypersensibilité', 'Indécision', 'Peur du conflit'],
    compatibleNumbers: [2, 4, 8],
  },
  3: {
    lifePathName: 'The Communicator',
    lifePathNameFr: 'Le Communicant',
    description: 'Creative, expressive, and inspiring.',
    descriptionFr: 'Vous êtes né pour vous exprimer et inspirer. Créatif et joyeux, vous apportez de la lumière partout.',
    strengths: ['Creativity', 'Expression', 'Optimism', 'Charisma'],
    strengthsFr: ['Créativité', 'Expression', 'Optimisme', 'Charisme'],
    challenges: ['Scattered energy', 'Criticism', 'Moodiness'],
    challengesFr: ['Énergie dispersée', 'Critique', 'Humeur changeante'],
    compatibleNumbers: [3, 6, 9],
  },
  4: {
    lifePathName: 'The Builder',
    lifePathNameFr: 'Le Bâtisseur',
    description: 'Practical, organized, and hardworking.',
    descriptionFr: 'Vous êtes né pour construire des fondations solides. Pratique et travailleur, vous créez la stabilité.',
    strengths: ['Organization', 'Dedication', 'Reliability', 'Practicality'],
    strengthsFr: ['Organisation', 'Dévouement', 'Fiabilité', 'Sens pratique'],
    challenges: ['Rigidity', 'Stubbornness', 'Workaholism'],
    challengesFr: ['Rigidité', 'Entêtement', 'Surmenage'],
    compatibleNumbers: [2, 4, 8],
  },
  5: {
    lifePathName: 'The Adventurer',
    lifePathNameFr: 'L\'Aventurier',
    description: 'Freedom-loving, versatile, and dynamic.',
    descriptionFr: 'Vous êtes né pour l\'aventure et le changement. Libre et adaptable, vous explorez toutes les possibilités.',
    strengths: ['Adaptability', 'Freedom', 'Curiosity', 'Versatility'],
    strengthsFr: ['Adaptabilité', 'Liberté', 'Curiosité', 'Polyvalence'],
    challenges: ['Restlessness', 'Impulsiveness', 'Inconsistency'],
    challengesFr: ['Agitation', 'Impulsivité', 'Inconstance'],
    compatibleNumbers: [1, 5, 7],
  },
  6: {
    lifePathName: 'The Nurturer',
    lifePathNameFr: 'Le Protecteur',
    description: 'Caring, responsible, and family-oriented.',
    descriptionFr: 'Vous êtes né pour prendre soin des autres. Responsable et aimant, vous créez un foyer harmonieux.',
    strengths: ['Nurturing', 'Responsibility', 'Love', 'Healing'],
    strengthsFr: ['Protection', 'Responsabilité', 'Amour', 'Guérison'],
    challenges: ['Self-sacrifice', 'Control', 'Perfectionism'],
    challengesFr: ['Sacrifice de soi', 'Contrôle', 'Perfectionnisme'],
    compatibleNumbers: [3, 6, 9],
  },
  7: {
    lifePathName: 'The Seeker',
    lifePathNameFr: 'Le Chercheur',
    description: 'Analytical, spiritual, and introspective.',
    descriptionFr: 'Vous êtes né pour chercher la vérité. Analytique et spirituel, vous explorez les mystères de la vie.',
    strengths: ['Wisdom', 'Intuition', 'Analysis', 'Spirituality'],
    strengthsFr: ['Sagesse', 'Intuition', 'Analyse', 'Spiritualité'],
    challenges: ['Isolation', 'Over-thinking', 'Skepticism'],
    challengesFr: ['Isolement', 'Sur-analyse', 'Scepticisme'],
    compatibleNumbers: [1, 5, 7],
  },
  8: {
    lifePathName: 'The Achiever',
    lifePathNameFr: 'L\'Accomplisseur',
    description: 'Ambitious, powerful, and successful.',
    descriptionFr: 'Vous êtes né pour réussir et accomplir. Ambitieux et puissant, vous atteignez vos objectifs.',
    strengths: ['Ambition', 'Power', 'Success', 'Authority'],
    strengthsFr: ['Ambition', 'Pouvoir', 'Succès', 'Autorité'],
    challenges: ['Materialism', 'Workaholism', 'Control issues'],
    challengesFr: ['Matérialisme', 'Surmenage', 'Problèmes de contrôle'],
    compatibleNumbers: [2, 4, 8],
  },
  9: {
    lifePathName: 'The Humanitarian',
    lifePathNameFr: 'L\'Humanitaire',
    description: 'Compassionate, idealistic, and generous.',
    descriptionFr: 'Vous êtes né pour servir l\'humanité. Compatissant et idéaliste, vous œuvrez pour un monde meilleur.',
    strengths: ['Compassion', 'Generosity', 'Idealism', 'Creativity'],
    strengthsFr: ['Compassion', 'Générosité', 'Idéalisme', 'Créativité'],
    challenges: ['Martyrdom', 'Scattered focus', 'Letting go'],
    challengesFr: ['Martyrisme', 'Dispersion', 'Lâcher-prise'],
    compatibleNumbers: [3, 6, 9],
  },
  11: {
    lifePathName: 'The Visionary',
    lifePathNameFr: 'Le Visionnaire',
    description: 'Intuitive, inspiring, and spiritually awakened.',
    descriptionFr: 'Nombre maître. Vous êtes né pour inspirer et illuminer. Intuitif et visionnaire, vous portez une lumière spirituelle.',
    strengths: ['Inspiration', 'Intuition', 'Vision', 'Charisma'],
    strengthsFr: ['Inspiration', 'Intuition', 'Vision', 'Charisme'],
    challenges: ['Nervous tension', 'Self-doubt', 'Over-sensitivity'],
    challengesFr: ['Tension nerveuse', 'Doute de soi', 'Hypersensibilité'],
    compatibleNumbers: [2, 11, 22],
  },
  22: {
    lifePathName: 'The Master Builder',
    lifePathNameFr: 'Le Maître Bâtisseur',
    description: 'Powerful manifestor and builder of dreams.',
    descriptionFr: 'Nombre maître. Vous êtes né pour réaliser de grandes choses. Vous avez le pouvoir de concrétiser vos visions à grande échelle.',
    strengths: ['Manifestation', 'Leadership', 'Vision', 'Practicality'],
    strengthsFr: ['Manifestation', 'Leadership', 'Vision', 'Sens pratique'],
    challenges: ['Pressure', 'Overwhelm', 'Self-doubt'],
    challengesFr: ['Pression', 'Surcharge', 'Doute de soi'],
    compatibleNumbers: [4, 11, 22],
  },
  33: {
    lifePathName: 'The Master Teacher',
    lifePathNameFr: 'Le Maître Enseignant',
    description: 'Ultimate healer and spiritual teacher.',
    descriptionFr: 'Nombre maître rare. Vous êtes né pour guérir et enseigner. Votre mission est d\'élever la conscience collective.',
    strengths: ['Healing', 'Teaching', 'Compassion', 'Devotion'],
    strengthsFr: ['Guérison', 'Enseignement', 'Compassion', 'Dévouement'],
    challenges: ['Self-sacrifice', 'Martyrdom', 'Perfectionism'],
    challengesFr: ['Sacrifice de soi', 'Martyrisme', 'Perfectionnisme'],
    compatibleNumbers: [6, 9, 33],
  },
};

// ============================================
// Matrice de compatibilité entre signes
// ============================================

export const COMPATIBILITY_MATRIX: Record<ZodiacSignKey, Record<ZodiacSignKey, number>> = {
  aries: { aries: 75, taurus: 45, gemini: 85, cancer: 42, leo: 95, virgo: 50, libra: 70, scorpio: 55, sagittarius: 93, capricorn: 47, aquarius: 78, pisces: 67 },
  taurus: { aries: 45, taurus: 80, gemini: 40, cancer: 90, leo: 55, virgo: 92, libra: 65, scorpio: 88, sagittarius: 35, capricorn: 95, aquarius: 42, pisces: 85 },
  gemini: { aries: 85, taurus: 40, gemini: 70, cancer: 55, leo: 88, virgo: 68, libra: 93, scorpio: 45, sagittarius: 78, capricorn: 50, aquarius: 95, pisces: 52 },
  cancer: { aries: 42, taurus: 90, gemini: 55, cancer: 75, leo: 65, virgo: 80, libra: 48, scorpio: 95, sagittarius: 40, capricorn: 58, aquarius: 45, pisces: 98 },
  leo: { aries: 95, taurus: 55, gemini: 88, cancer: 65, leo: 78, virgo: 52, libra: 85, scorpio: 60, sagittarius: 97, capricorn: 45, aquarius: 72, pisces: 55 },
  virgo: { aries: 50, taurus: 92, gemini: 68, cancer: 80, leo: 52, virgo: 72, libra: 58, scorpio: 88, sagittarius: 45, capricorn: 95, aquarius: 48, pisces: 65 },
  libra: { aries: 70, taurus: 65, gemini: 93, cancer: 48, leo: 85, virgo: 58, libra: 75, scorpio: 52, sagittarius: 88, capricorn: 55, aquarius: 95, pisces: 62 },
  scorpio: { aries: 55, taurus: 88, gemini: 45, cancer: 95, leo: 60, virgo: 88, libra: 52, scorpio: 85, sagittarius: 42, capricorn: 78, aquarius: 48, pisces: 97 },
  sagittarius: { aries: 93, taurus: 35, gemini: 78, cancer: 40, leo: 97, virgo: 45, libra: 88, scorpio: 42, sagittarius: 80, capricorn: 48, aquarius: 90, pisces: 52 },
  capricorn: { aries: 47, taurus: 95, gemini: 50, cancer: 58, leo: 45, virgo: 95, libra: 55, scorpio: 78, sagittarius: 48, capricorn: 82, aquarius: 52, pisces: 70 },
  aquarius: { aries: 78, taurus: 42, gemini: 95, cancer: 45, leo: 72, virgo: 48, libra: 95, scorpio: 48, sagittarius: 90, capricorn: 52, aquarius: 75, pisces: 58 },
  pisces: { aries: 67, taurus: 85, gemini: 52, cancer: 98, leo: 55, virgo: 65, libra: 62, scorpio: 97, sagittarius: 52, capricorn: 70, aquarius: 58, pisces: 80 },
};

// ============================================
// Citations de fallback
// ============================================

export const FALLBACK_QUOTES: { text: string; author: string }[] = [
  { text: "L'univers conspire toujours en faveur de ceux qui rêvent.", author: "Paulo Coelho" },
  { text: "Soyez le changement que vous voulez voir dans le monde.", author: "Gandhi" },
  { text: "La vie est un mystère qu'il faut vivre, non un problème à résoudre.", author: "Gandhi" },
  { text: "Chaque instant est un nouveau commencement.", author: "T.S. Eliot" },
  { text: "La paix vient de l'intérieur. Ne la cherchez pas à l'extérieur.", author: "Bouddha" },
  { text: "Vous êtes ce que vous pensez. Tout ce que vous êtes naît de vos pensées.", author: "Bouddha" },
  { text: "Le bonheur n'est pas quelque chose de tout fait. Il vient de vos propres actions.", author: "Dalaï Lama" },
  { text: "L'amour est la seule réponse à la question de l'existence humaine.", author: "Erich Fromm" },
  { text: "Croyez en vous et tout devient possible.", author: "Anonyme" },
  { text: "Les étoiles ne brillent que dans l'obscurité.", author: "Anonyme" },
];

export const FALLBACK_AFFIRMATIONS: string[] = [
  "Je suis digne d'amour et de respect.",
  "Je choisis la paix et la sérénité.",
  "Chaque jour, je deviens une meilleure version de moi-même.",
  "Je suis guidé par la sagesse de l'univers.",
  "J'accepte les bénédictions qui viennent à moi.",
  "Je libère ce qui ne me sert plus.",
  "Mon énergie attire les bonnes personnes dans ma vie.",
  "Je fais confiance au timing parfait de l'univers.",
  "Je suis connecté à mon intuition.",
  "L'abondance coule librement vers moi.",
];
